// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU_GfgJBCGQofRftauWZllGEDfI57q4Mw',
    appId: '1:358270623507:web:f8f8baddffd0b0748144e6',
    messagingSenderId: '358270623507',
    projectId: 'asicity',
    authDomain: 'asicity.firebaseapp.com',
    storageBucket: 'asicity.firebasestorage.app',
    measurementId: 'G-WZ5BMT73QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw-0I37eHbB5oh1xQitoXqJhZAALzKQm0',
    appId: '1:358270623507:android:7e60b0ac18b00f1e8144e6',
    messagingSenderId: '358270623507',
    projectId: 'asicity',
    storageBucket: 'asicity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXhtcKM0YHmGYl-uiwls8XlA5TvGGBTRw',
    appId: '1:358270623507:ios:9e5e58a303ffa4338144e6',
    messagingSenderId: '358270623507',
    projectId: 'asicity',
    storageBucket: 'asicity.firebasestorage.app',
    iosBundleId: 'com.example.asicity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXhtcKM0YHmGYl-uiwls8XlA5TvGGBTRw',
    appId: '1:358270623507:ios:9e5e58a303ffa4338144e6',
    messagingSenderId: '358270623507',
    projectId: 'asicity',
    storageBucket: 'asicity.firebasestorage.app',
    iosBundleId: 'com.example.asicity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU_GfgJBCGQofRftauWZllGEDfI57q4Mw',
    appId: '1:358270623507:web:b7a356aed6003b738144e6',
    messagingSenderId: '358270623507',
    projectId: 'asicity',
    authDomain: 'asicity.firebaseapp.com',
    storageBucket: 'asicity.firebasestorage.app',
    measurementId: 'G-C947LFSFGV',
  );
}
